version: '3.8'
services:
    warranty:
        image: "warranty"
        container_name: warranty_app
        ports:
            - 8000:8000
        volumes:
            - warranty:/app/instance/
        env_file:
            - ./.env

volumes:
    warranty: